### ISSUE TITLE
【新固件】支持 R2S

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#155]
Alpha 固件已经发布：

https://fw.koolcenter.com/iStoreOS/alpha/

测试内容：

1. 刷写固件
2. 安装一些插件
3. 离线安装一些插件
4. 重新升级插件，保留配置，看看插件还在不在

**Comment by StefanLuo** [comment]
宝哥，R2S刷了所有的版本都没法开机，通电后网卡都不亮，只有电源指示灯亮。对于TF卡和写盘工具有什么要求吗？

**Comment by ericsnow911** [comment]
> 宝哥，R2S刷了所有的版本都没法开机，通电后网卡都不亮，只有电源指示灯亮。对于TF卡和写盘工具有什么要求吗？
 
我试过SanDisk Industrial 8G、SanDisk Ultra 16G A1、SanDisk HIGH ENDURANCE 32G三种卡都能正常使用，写盘工具用的balenaEtcher，你可以参考一下。

**Comment by StefanLuo** [comment]
好的，感谢宝哥！

从 Windows 版邮件发送

发件人: ericsnow911
发送时间: 2022年6月12日 19:37
收件人: linkease/istoreos
抄送: StefanLuo; Manual
主题: Re: [linkease/istoreos] 【新固件】支持 R2S (Issue #155)

宝哥，R2S刷了所有的版本都没法开机，通电后网卡都不亮，只有电源指示灯亮。对于TF卡和写盘工具有什么要求吗？
我试过SanDisk Industrial 8G、SanDisk Ultra 16G A1、SanDisk HIGH ENDURANCE 32G三种卡都能正常使用，写盘工具用的balenaEtcher，你可以参考一下。

**Comment by ericsnow911** [comment]
> 好的，感谢宝哥！ 从 Windows 版邮件发送 发件人: ericsnow911 发送时间: 2022年6月12日 19:37 收件人: linkease/istoreos 抄送: StefanLuo; Manual 主题: Re: [linkease/istoreos] 【新固件】支持 R2S (Issue #155) 宝哥，R2S刷了所有的版本都没法开机，通电后网卡都不亮，只有电源指示灯亮。对于TF卡和写盘工具有什么要求吗？ 我试过SanDisk Industrial 8G、SanDisk Ultra 16G A1、SanDisk HIGH ENDURANCE 32G三种卡都能正常使用，写盘工具用的balenaEtcher，你可以参考一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

哥们，我不是宝哥😂，能帮到你就好

**Comment by StefanLuo** [comment]
😂，不好意思，总之非常感谢

从 Windows 版邮件发送

发件人: ericsnow911
发送时间: 2022年6月15日 23:07
收件人: linkease/istoreos
抄送: StefanLuo; Manual
主题: Re: [linkease/istoreos] 【新固件】支持 R2S (Issue #155)

好的，感谢宝哥！ 从 Windows 版邮件发送 发件人: ericsnow911 发送时间: 2022年6月12日 19:37 收件人: linkease/istoreos 抄送: StefanLuo; Manual 主题: Re: [linkease/istoreos] 【新固件】支持 R2S (Issue #155) 宝哥，R2S刷了所有的版本都没法开机，通电后网卡都不亮，只有电源指示灯亮。对于TF卡和写盘工具有什么要求吗？ 我试过SanDisk Industrial 8G、SanDisk Ultra 16G A1、SanDisk HIGH ENDURANCE 32G三种卡都能正常使用，写盘工具用的balenaEtcher，你可以参考一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.***>
哥们，我不是宝哥😂，能帮到你就好

**Comment by jannson** [comment]
目前 R2S 我们测试多次，都是可以的。我先关闭 issue，如果有问题呢，你们再来这个 issue 反馈。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3557/1
